### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by leonidussaks** [ffwff/lilith#17]
i try compile os

$ make toolchain/crystal/.build/crystal
cd toolchain/crystal && make release=1
make[1]: вход в каталог «/home/leonid/lilith/toolchain/crystal»
Makefile:69: *** Could not locate llvm-config, make sure it is installed and in your PATH, or set LLVM_CONFIG

**Comment by leonidussaks** [comment]
antix linux

**Comment by ffwff** [comment]
Can you try installing development libraries for LLVM?

**Comment by ghost** [comment]
e.g. `sudo apt-get install llvm-8-dev` recommended at the time of writing for debian based systems (that antix seems to be)

**Comment by leonidussaks** [comment]
i install this and build. i waited 2 hours and here
g++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/lib/llvm-7/include  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
cc -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_LIBRARY_PATH="/usr/bin/../lib/crystal/lib" CRYSTAL_CONFIG_BUILD_COMMIT="9e28451fb" ./bin/crystal build --release  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
fork: Out of memory (Errno)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

**Comment by ffwff** [comment]
You might want to buy more memory, I can't really help you with that :(
