### ISSUE TITLE
Question: Sources of some assets?

### ISSUE THREAD

**Issue by ghost** [ffwff/lilith#23]
Not trying to be rude or anything, just thought it would be safe to do the following?
1. The wallpaper
- [x] The original source of the painting? (Which I am genuinely curious BTW)
- [x]  ~~Attribution to "Machikado Mazoku"? You may get a fresh peach heart shower~~  
    I'm not sure how animation copyright works to suggest this.
2. The ISO Image?
- It contains GRUB which is GPL licensed, according to the [warning here](https://wiki.osdev.org/Bare_Bones#Building_a_bootable_cdrom_image).
- [x] Disclosure that the ISOs are under the GNU GPL, perhaps with a license?

**Comment by ffwff** [comment]
[Source](https://www.pixiv.net/en/artworks/57632304).

According to the studio's bio it's okay for private use but reprinting isn't.

I'm not sure if I'm violating any copyright rules but I may have to change it just to be safe.

**Comment by Scorbie** [comment]
I'm clueless as well, but the link above implies that you don't have to change the license of your project, but just have to distribute the bootloader source code along with the iso image.

**Comment by ffwff** [comment]
I created a new background, so hopefully we should be legal (purged the git repo just to be safe :P)
