### ISSUE TITLE
Plans on using git submodules?

### ISSUE THREAD

**Issue by ghost** [ffwff/lilith#28]
While I'm pretty certain not using submodules was a design decision,
I'd like to hear about your opinion on having build dependencies such as crystal, binutils, etc... as submodules.
BTW I would need some time if I get to implement this idea.
Edit: Congrats you have 900 stars!
~~I'll star your repo again cause I really like it~~

**Comment by ghost** [comment]
I guess this is a "Hooray, but No?"

**Comment by ffwff** [comment]
My plan is to only have OS-specific packages be submodules. For the toolchain or anything that can be handled by the build scripts, I won't add submodules for them.

**Comment by ghost** [comment]
I see, thanks :)
