### ISSUE TITLE
Error building gcc: commit does not exist

### ISSUE THREAD

**Issue by aunetx** [ffwff/lilith#33]
Hello,

When trying to build the userspace (with `cd userspace/toolchain` and then `make`), binutils are correctly patched and built but gcc fails with an error.

The commit id `4ac50a4913e` does not seems to be correct, and `git checkout 4ac50a4913e` (`userspace/toolchain/Makefile` line 21) fails with the error:
 `error: le spécificateur de chemin '4ac50a4913e' ne correspond à aucun fichier connu de git` (in french, literally the specified commit does not exist in the current git directory)

With that error, the compiler cannot be patched and built. Any idea of where could this come from ? Or what is the correct commit id (or git branch) to use so the patch works ?

Sorry if that's a newbie question, and excuse me for the English grammar

**Comment by aunetx** [comment]
I changed the commit id and adapted `gcc.patch` to this version, gcc building works and some packages can be built with missio.

Some others can't, like :
- `libpng` (`pkgs/.build/libpng-1.6.37/png.c:302: undefined reference to 'setjmp'`)
- `libcairo` (4 errors, all of them are `-Werror=implicit-function-declaration`)
- `libfreetype` (`checking host system type... Invalid configuration 'x86_64-elf-lilith': system 'lilith' not recognized`)
- and a lot like them...

If I can help in any way in development, I would be enchanted ; I can submit a PR for the gcc patch if needed (but I do not guarantee that it does not change anything about compilation)

**Comment by aunetx** [comment]
I created a PR here if interested, but it needs testing #34

**Comment by mtnygard** [comment]
I have the same error.

**Comment by aunetx** [comment]
Merged :)
