### ISSUE TITLE
Can it run Quake?

### ISSUE THREAD

**Issue by sdogruyol** [ffwff/lilith#7]
No pun intented and taken from Reddit

https://www.reddit.com/r/opensource/comments/dkf9h7/fully_working_posixlike_x8664_os_in_crystal/f4dxcbp/

**Comment by ffwff** [comment]
No.

Please view my response in the thread ~~and get back to me in like 6-9 months~~

**Comment by sdogruyol** [comment]
Seems like next year https://www.reddit.com/r/opensource/comments/dkf9h7/fully_working_posixlike_x8664_os_in_crystal/f4f15o2/

Closing for now :+1:
